name = "gmail-cleanup-cron"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "3c935156bf9683f48b9f259010f22622"

[triggers]
crons = ["0 */6 * * *"]

[vars]
GITHUB_OWNER = "Chr15t1an"
GITHUB_REPO = "gmail-inbox-helpper"

# GITHUB_TOKEN is set via `wrangler secret put GITHUB_TOKEN`
